Name: examservice
Build: local
App: 
Controller: 
  Name: HTTP
  HTTP:
    Port: 8080
    GinModeDebug: false
Repository:
  Name: Mongo
  Mongo: 
    Host: localhost:27017
    Database: examservice
    UserName: bappa
    Password: bappa