definitions:
  dto.AnswerRequest:
    properties:
      _id:
        type: string
      answers:
        items:
          $ref: '#/definitions/dto.QuestionAnswer'
        type: array
      examId:
        type: string
      userId:
        type: string
    type: object
  dto.AnswerResponse:
    properties:
      _id:
        type: string
      statusCode:
        type: integer
    type: object
  dto.Choice:
    properties:
      key:
        type: string
      value:
        type: string
    type: object
  dto.Exam:
    properties:
      _id:
        type: string
      created_at:
        type: integer
      description:
        type: string
      difficulty_level:
        type: string
      duration:
        type: integer
      end_time:
        type: integer
      exam_fee:
        type: number
      questions:
        items:
          type: string
        type: array
      start_time:
        type: integer
      sub_topic:
        type: string
      title:
        type: string
      topic:
        type: string
      updated_at:
        type: integer
    type: object
  dto.ExamRequest:
    properties:
      _id:
        type: string
      description:
        type: string
      difficulty_level:
        type: string
      duration:
        type: integer
      end_time:
        type: integer
      exam_fee:
        type: number
      questions:
        items:
          type: string
        type: array
      start_time:
        type: integer
      sub_topic:
        type: string
      title:
        type: string
      topic:
        type: string
    type: object
  dto.ExamResponse:
    properties:
      _id:
        type: string
      statusCode:
        type: integer
    type: object
  dto.ListExamsResponse:
    properties:
      exam:
        items:
          $ref: '#/definitions/dto.Exam'
        type: array
      statusCode:
        type: integer
    type: object
  dto.ListQuestionResponse:
    properties:
      questions:
        items:
          $ref: '#/definitions/dto.Question'
        type: array
      statusCode:
        type: integer
    type: object
  dto.PingResponse:
    properties:
      message: {}
      statusCode:
        type: integer
    type: object
  dto.Question:
    properties:
      _id:
        type: string
      choices:
        items:
          $ref: '#/definitions/dto.Choice'
        type: array
      correct:
        type: string
      created_at:
        type: integer
      explanation:
        type: string
      text:
        type: string
      updated_at:
        type: integer
      userId:
        type: string
    type: object
  dto.QuestionAnswer:
    properties:
      answer:
        type: string
      questionId:
        type: string
    type: object
  dto.QuestionRequest:
    properties:
      _id:
        type: string
      choices:
        items:
          $ref: '#/definitions/dto.Choice'
        type: array
      correct:
        type: string
      explanation:
        type: string
      text:
        type: string
      userId:
        type: string
    type: object
  dto.QuestionResponse:
    properties:
      _id:
        type: string
      statusCode:
        type: integer
    type: object
  utils.CustomError:
    properties:
      message:
        type: string
      statusCode:
        type: integer
    type: object
info:
  contact: {}
paths:
  /examservice/answers/submit:
    post:
      consumes:
      - application/json
      description: Creates or updates an answer based on the provided request body.
      parameters:
      - description: Answer request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.AnswerRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successful operation
          schema:
            $ref: '#/definitions/dto.AnswerResponse'
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/utils.CustomError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/utils.CustomError'
      summary: Create or update answer
      tags:
      - Answers
  /examservice/exams:
    post:
      consumes:
      - application/json
      description: Create a new exam or update an existing one based on the provided
        request body.
      parameters:
      - description: Exam request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.ExamRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successful response
          schema:
            $ref: '#/definitions/dto.ExamResponse'
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/utils.CustomError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/utils.CustomError'
      summary: Create or update an exam
      tags:
      - Exams
  /examservice/exams/:
    get:
      consumes:
      - application/json
      description: Retrieve a list of all exams filtered by topic and subTopic.
      parameters:
      - description: Filter by topic
        in: query
        name: topic
        type: string
      - description: Filter by subTopic
        in: query
        name: subTopic
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful response
          schema:
            items:
              $ref: '#/definitions/dto.ListExamsResponse'
            type: array
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/utils.CustomError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/utils.CustomError'
      summary: Get all exams
      tags:
      - Exams
  /examservice/exams/{id}:
    delete:
      consumes:
      - application/json
      description: Deletes an exam by its ID.
      parameters:
      - description: Exam ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful response
          schema:
            $ref: '#/definitions/dto.ExamResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/utils.CustomError'
        "404":
          description: Exam not found
          schema:
            $ref: '#/definitions/utils.CustomError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/utils.CustomError'
      summary: Delete an exam by ID
      tags:
      - Exams
  /examservice/ping/:
    get:
      description: Pings the server and returns "Okay" if successful.
      parameters:
      - description: Flag indicating whether to ping the database
        in: query
        name: db
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.PingResponse'
      summary: Pings the server.
      tags:
      - Ping
  /examservice/questions:
    post:
      consumes:
      - application/json
      description: Create or update questions based on the request
      parameters:
      - description: Question request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.QuestionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully created or updated questions
          schema:
            $ref: '#/definitions/dto.QuestionResponse'
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/utils.CustomError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/utils.CustomError'
      summary: Create or update questions
      tags:
      - Questions
  /examservice/questions/:
    get:
      consumes:
      - application/json
      description: Retrieve a list of all questions.
      produces:
      - application/json
      responses:
        "200":
          description: Successful response
          schema:
            items:
              $ref: '#/definitions/dto.ListQuestionResponse'
            type: array
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/utils.CustomError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/utils.CustomError'
      summary: Get all questions
      tags:
      - Questions
  /examservice/questions/{id}:
    delete:
      consumes:
      - application/json
      description: Deletes a question by its ID.
      parameters:
      - description: Question ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful response
          schema:
            $ref: '#/definitions/dto.QuestionResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/utils.CustomError'
        "404":
          description: Question not found
          schema:
            $ref: '#/definitions/utils.CustomError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/utils.CustomError'
      summary: Delete a question by ID
      tags:
      - Questions
swagger: "2.0"
